Sender chat colors
wokenet/anchor pull request #4
Opened 2020-12-13 04:31 UTC by ccrabb

The only real ReactJS decision I feel like I made here was to add `senderColor` as a parameter to the `Message` component. Originally I applied the color via the ReactJS `color` property, but then it made the TSX markup a bit unwieldy. All feedback welcome!

2020-12-17 22:40 UTC, chromakode requested changes
Great work! A couple small requests before we ship this.

2020-12-17 22:40 UTC, chromakode commented on src/pages/index.tsx
> +]
Let's hold off from differentiating admins right now and split this into a separate project / discussion. I'm not sure if/how we'd like to display this, and the status should be sourced from the matrix user "power level" (>=50 means the user is a mod, 100 means the user is an admin)

2020-12-17 22:40 UTC, chromakode commented on src/pages/index.tsx
> +
Could you please move these functions to a separate file -- perhaps `src/colors.ts`?

2020-12-17 22:40 UTC, chromakode commented on src/pages/index.tsx
> -                    _odd={{ backgroundColor: 'gray.900' }}
I'd like to retain the even/odd background coloring for now.

2020-12-17 22:40 UTC, chromakode commented on src/pages/index.tsx
> +              {messageText.length > 250 ? <small>{messageText.length}/500</small> : null}
Ooo This is awesome. I'd like to see how this looks -- I've tweaked our Netlify settings to the next time you push it'll build a site preview for us to check out. In the future, could you please split out separate features like this into different PRs? Will make it faster to review/merge things piecemeal.

2020-12-17 22:43 UTC, chromakode requested changes

2020-12-17 22:43 UTC, chromakode commented on src/pages/index.tsx
> +              {messageText.length > 250 ? <small>{messageText.length}/500</small> : null}
One more thought: the 500 char limit is a pretty important global value. Could you please move it to https://github.com/wokenet/anchor/blob/main/constants.json?

2020-12-18 04:00 UTC, ccrabb commented on src/pages/index.tsx
> +              {messageText.length > 250 ? <small>{messageText.length}/500</small> : null}
Yep to both!

2020-12-18 04:00 UTC, ccrabb commented on src/pages/index.tsx
> -                    _odd={{ backgroundColor: 'gray.900' }}
Okay

2020-12-18 04:01 UTC, chromakode commented on src/pages/index.tsx
> +                </InputRightElement>
Could we please hide this when no limit is near, so it doesn't constrain the available text space?

```suggestion
                {messageText.length > 250 && (
                  <InputRightElement flexShrink={0} width={50} height={50}>
                    <small>{maximumMessageSize-messageText.length}</small>
                  </InputRightElement>
                }
```

2020-12-18 04:09 UTC, chromakode commented on src/pages/index.tsx
> +                <InputRightElement flexShrink={0} width={50} height={50}>
We should make the limit text unselectable with:

```suggestion
                <InputRightElement flexShrink={0} width={50} height={50} pointerEvents="none">
```

2020-12-18 04:23 UTC, chromakode approved these changes

2020-12-18 04:28 UTC, merged